### ISSUE TITLE
Can generate automatic annotations using some annotated RFCs

### ISSUE THREAD

**Issue by panhao410** [RFCNLP/RFCNLP#3]
Hello，through the preliminary understanding of the project, I want to know whether the annotated RFC can be automatically generated through Bert and annotated RFCs

**Comment by maxvonhippel** [comment]
The answer is yes, although annotations produced by a model (`LinearCRF+R` or `NeuralCRF+R`) are not expected to be quite as good as those written by hand (what we call "Gold" intermediary representations).

If you'd like instructions on how to do this for an arbitrary protocol specification document, we have an open issue for that, [HERE](https://github.com/RFCNLP/RFCNLP/issues/2), which @mlpacheco will address at some point in the future.  This is entirely possible to do but will require some light modification of our code as the existing code has the RFC document paths hard-coded.  Note that as currently configured this repo only promises to reproduce our results from S&P 2022; it does not yet make it easy to generate new results.

Thanks for your interest!
