### ISSUE TITLE
About canonical FSM

### ISSUE THREAD

**Issue by haidequanbu** [RFCNLP/RFCNLP#7]
Hello, there are some unclear points for the diagram of the best state machine in the paper, please ask if it is convenient to provide a representation of the state machine's triplet, for example ( CLOSING, {ACK?}, TIME_WAIT), if disturbed, please forgive and appreciate!
![image](https://user-images.githubusercontent.com/67882439/190654380-d5b70ace-ec81-4827-9076-d5a6a28f2a1b.png)
The part with the blue line are the transitions I don't know much about，and thanks a lot！

**Comment by maxvonhippel** [comment]
The best clarification is to just look at [the Promela code](https://github.com/RFCNLP/RFCNLP/blob/main/promela-models/DCCP/Canonical-Test-Client-Server/canonical.DCCP.client.server.pml#L49).  You can consult the [Spin documentation](http://spinroot.com/) to understand the code.  Thanks for your interest!
