### ISSUE TITLE
FSM results  evaluate

### ISSUE THREAD

**Issue by haidequanbu** [RFCNLP/RFCNLP#8]
Hello，I am a student who is insterested in your work!
And during following your work,I meet some problems about FSM  results  evaluate.
How to evaluate the correctness of the extracted state machine, is it manual comparison or automation? Is the state machine triple or the .pml file in the result being comparing?
<img width="588" alt="image" src="https://user-images.githubusercontent.com/67882439/190848636-de77bc29-985c-4ee2-b32e-1e29bc046d86.png">
That's to say,how can I get the similar results as the table above?Is that anying(such as code off-shelf) available we can use?
Thanks a lot for your reply!

**Comment by maxvonhippel** [comment]
If you simply run the code, it prints all these outputs in an ASCII table for you.  You can use the Makefile for this, e.g., the TCP Gold row can be derived using `make tcp`.
