### ISSUE TITLE
rfcs-annotated-tidied folder can't  generate  automatically

### ISSUE THREAD

**Issue by cheif-zyo** [RFCNLP/RFCNLP#9]
Hello!
If I wanto try new RFC ,such as DHCP.Do I have to write rfcs-annotated-tidied/DHCP.xml by hand?

**Comment by maxvonhippel** [comment]
No, if you have `rfcs-annotated/DHCP.txt` then you get the tided version automatically by running `python3 utils/tidy_documents.py`.  You will however need to write `rfcs-annotated/DHCP.txt` by hand, that is, unless all you want to do is rely on the pre-trained models to annotate for you (and we make no guarantees about how well they will do this ...)
